# Generated by Django 4.1.2 on 2022-10-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='porjects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=201, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
